---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
  namespace: hello
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flux
    spec:
      # The serviceAccount is only needed for Kubernetes with RBAC
      serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
      containers:
      - name: fluxd
        image: quay.io/weaveworks/flux:master-7b742aa
        imagePullPolicy: Never
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        args:
        - --memcached-hostname=memcached.hello.svc.cluster.local
        - --memcached-timeout=100ms
        - --memcached-service=memcached
        - --registry-cache-expiry=20m
        - --git-url=git@github.com:squaremo/flux-example
        - --git-branch=gitsync
        - --token=local-test-token
        - --connect=ws://authfe.default.svc.cluster.local/api/flux
