apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-two
spec:
  replicas: 6
  template:
    metadata:
      labels:
        name: helloworld-two
    spec:
      containers:
      - name: helloworld
        image: quay.io/weaveworks/helloworld:master-a000002
        args:
        - -msg="Ahoy Two"
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
