apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-master-a000001
spec:
  replicas: 2
  selector:
    name: helloworld
    version: master-a000001
  template:
    metadata:
      labels:
        name: helloworld
        version: master-a000001
    spec:
      containers:
      - name: helloworld
        image: quay.io/weaveworks/helloworld:master-a000001
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80