apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-alt
  labels:
    name: hello-alt
spec:
  replicas: 4
  selector:
    matchLabels:
      name: hello-alt
  template:
    metadata:
      labels:
        name: hello-alt
    spec:
      containers:
      - name: hello-alt
        image: quay.io/squaremo/hello_world:master-a000001
        imagePullPolicy: Always
        env:
          - name: GET_HOSTS_FROM
            value: dns
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
      restartPolicy: Always
