apiVersion: v1
kind: ReplicationController
metadata:
  name: worldhello-master-a000001
spec:
  minReadySeconds: 1
  replicas: 5
  template:
    metadata:
      labels:
        name: worldhello
    spec:
      containers:
      - name: helloworld
        image: quay.io/squaremo/hello_world:master-a000001
        args:
        - -msg=Kiaora
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: docker
      restartPolicy: Always
