---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxd
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxd
    spec:
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
#          defaultMode: 0400 # ignored by Kubernetes < 1.6
      containers:
      - name: fluxd
        image: quay.io/squaremo/fluxd
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: git-key
          mountPath: /secrets/flux/git
        args:
        - --git-url=git@github.com:squaremo/flux-example
        - --git-key=/secrets/flux/git/id-rsa-flux
        - --connect=ws://authfe.default.svc.cluster.local/api/flux
        - --token=pj38xti4qc3zaz1n4afyc675g3kzf88a
