---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxsvc
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxsvc
    spec:
      containers:
      - name: fluxsvc
        image: quay.io/squaremo/fluxsvc:metrics
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
        args:
        - --database-source=postgres://postgres:password@postgres.fluxy.svc.cluster.local:5432?sslmode=disable
#        - --nats-url=nats://nats:4222
