---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxd
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxd
    spec:
      containers:
      - name: fluxd
        image: quay.io/weaveworks/fluxd
        imagePullPolicy: IfNotPresent
        args:
        - --token=z1z3zj4mwp1j49symcx4nsxoe8xr7gc7
        #  connect to the local service
        - --fluxsvc-address=ws://frontend.default.svc.cluster.local/api/flux
