---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nats
  namespace: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nats
    spec:
      containers:
      - name: nats
        image: library/nats:0.9.4
        imagePullPolicy: IfNotPresent
        args:
        - nats
